# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Magic Judges BR
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Esse projeto visa disponibilizar as regras de Magic: The Gathering® em português,
  para que mais pessoas possam ter acesso.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://magicjudgesbr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
#theme: just-the-docs
search_enabled: true
include: [_i18n]

# the files that are ignored by jekyll.
# This variable is automatically filled to avoid build loops

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - crowdin.yml
