# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Github Pages deploy

on:
  push:
    branches: [ l10n_develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt-get install -y gettext
    - name: Generate i18n data
      run: |
        msguniq data/pt/LC_MESSAGES/comprehensive-rules.po --output data/pt/LC_MESSAGES/comprehensive-rules.po
        msgfmt data/pt/LC_MESSAGES/comprehensive-rules.po --output data/pt/LC_MESSAGES/comprehensive-rules.mo
    - name: Build static data
      run: python build.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
